---
abstract: "YAML Ain't Markup Language™"
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  Test::YAML: '1.05'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: YAML
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/yaml-pm/issues
  homepage: https://github.com/ingydotnet/yaml-pm
  repository: https://github.com/ingydotnet/yaml-pm.git
version: '1.15'
